image: registry.fedoraproject.org/fedora-minimal:36

linux:
  stage: build
  script:
    - microdnf install -y git clang fontconfig-devel freetype-devel libvorbis-devel libepoxy-devel libwebp-devel boost-python3-devel python3-devel cmake ninja-build SDL2-devel openal-soft-devel clang-tools-extra python3-PyYAML libcxx-devel libasan libatomic >/dev/null
    - cmake -GNinja -Bbuild-linux
    - cd build-linux
    - TERM=xterm script -qfec "ninja jnglexample" /dev/null
    - cd -
    - CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -GNinja -Bbuild-linux-clang
    - cd build-linux-clang
    - TERM=xterm script -qfec "ninja jnglexample" /dev/null

windows:
  stage: build
  script:
    - microdnf install -y cmake ninja-build mingw32-pkg-config mingw32-libvorbis mingw32-SDL2 mingw32-fontconfig mingw32-libwebp mingw32-boost mingw32-dlfcn mingw32-libepoxy mingw32-openal-soft mingw32-nsis git >/dev/null
    - mingw32-cmake -Bbuild-windows -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0
    - ninja -Cbuild-windows jnglexample.exe
    - makensis windows/installer.nsi
  artifacts:
    paths:
      - Project Schranke Setup.exe


web:
  stage: build
  image: emscripten/emsdk:3.1.21
  script:
    - apt-get update && apt-get install -y ninja-build
    - emcmake cmake -GNinja -Bbuild-web -DCMAKE_BUILD_TYPE=Release -DJNGL_VIDEO=0
    - cp -r data build-web/data
    - ninja -Cbuild-web

    - rm -r CMakeFiles CMakeCache.txt Makefile _deps cmake_install.cmake include subprojects
  artifacts:
    paths:
      - build-web/

variables:
  GIT_SUBMODULE_STRATEGY: recursive


pages:
  stage: deploy
  dependencies:
    - web
  script:
  - cp -r build public
  artifacts:
    paths:
    - public
  # only:
  # - master
